theme: minima
title: How much I love coding!!!
author: JMori6
email: jmori6@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  I love coding because I find it is a great way to express yourself in a new way by making webpages. All you have to do is learn all the cool HTML tags and CSS style tags and you can make the coolest websites!
My favourite HTML are the list tags, title tags and header tags. My favourite CSS tags are background color, font family and font size. 
# social links
github_username:  JMori6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
